### ISSUE TITLE
volatility how to run this

### ISSUE THREAD

**Issue by littleheary** [exp0se/volatility-plugins#1]
i don't know how to run this.
when i run
volatility -f Target.vmem --profile=Win7SP1x64 vmtools
it is no use.

**Comment by littleheary** [comment]
i have find this , but have error

                win_vmtools_command     Extract commands run via Vmware tools
➜  /tmp volatility -f Target.vmem --profile=Win7SP1x64 win_vmtools_comman
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : You must specify something to do (try -h)
➜  /tmp volatility -f Target.vmem --profile=Win7SP1x64 win_vmtools_command
Volatility Foundation Volatility Framework 2.6
Process          Pid      Address            Command                                            Login                          Password                       Command Data
---------------- -------- ------------------ -------------------------------------------------- ------------------------------ ------------------------------ ------------
Traceback (most recent call last):
  File "/usr/bin/volatility", line 192, in <module>
    main()
  File "/usr/bin/volatility", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/vmtools.py", line 563, in render_text
    for (task, address, opcode, login, password, cmd_data) in data:
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/vmtools.py", line 546, in calculate
    for offset, command, opcode, credential_type, cmd_data_size in scanner.scan():
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/vmtools.py", line 284, in scan
    for hit, address in malfind.BaseYaraScanner.scan(self, vad.Start, vad.Length):
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/malware/malfind.py", line 114, in scan
    for moffset, _name, _value in match.strings:
AttributeError: 'str' object has no attribute 'strings'
